# -*- coding: utf-8 -*-
{
    'name': "Airline Supply Chain Automation",
    'summary': """ This is an airline ticketing model that will generate a purchase order and a sell order on every ticket creation. """,
    'description': """ This is an airline ticketing model that will generate a purchase order and a sell order on every ticket creation. """,
    'author': "AliFaleh@BasicPowered",
    'website': "https://site.basic-powered.com",
    'category': 'Ticketing',
    'version': '17.0',
    'depends': [
        'base', 
        'contacts', 
        'sale_management', 
        'purchase', 
        'mail', 
        'stock',
        'sale_order_automation',
        'purchase_order_automation',
        'crm',
        'helpdesk',
        'account',
        'account_reports',
    ],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/product_template.xml',
        'data/partner_ledger.xml',
        'data/report_paperformat.xml',
        'wizard/final_finance_report.xml',
        'wizard/external_partner_ledger.xml',
        'wizard/external_general_ledger.xml',
        'data/general_ledger.xml',
        'views/account_partner_ledger_audit.xml',
        'views/account_general_ledger_audit.xml',
        'views/views.xml',
        'views/airline_ticket.xml',
        'views/airline_tour.xml',
        'views/airline_visa.xml',
        'views/airline_mpayment.xml',
        'views/res_partner.xml',
        'views/report_templates.xml',
        'views/res_company.xml',
        'views/account.xml',
        'views/account_payment.xml',
        'views/account_move_line.xml',
        'views/account_report_column.xml',
        'wizard/ticket_reverse.xml',
        'wizard/tour_reverse.xml',
        'wizard/visa_reverse.xml',
        'wizard/mpayment_reverse.xml',
        'report/report.xml',
        'report/external_partner_ledger_report.xml',
        'report/external_general_ledger_report.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'airline_sc_automation/static/src/css/style.css',
        ],
    },
    'application': True,
    'license': 'Other proprietary',
}