{
    2083: {
        (3528, datetime.date(2023, 9, 2)): {
            "(('forced_options', (('date', (('date_from', '2023-01-01'), ('date_to', '2023-12-31'), ('filter', 'this_year'), ('mode', 'range'), ('period_type', 'fiscalyear'), ('string', '2023'))),)), ('horizontal_groupby_element', ()))": {
                'id': 3528,
                'date': datetime.date(2023, 9, 2),
                'date_maturity': None,
                'name': 'توصيل وارسوا',
                'ref': None,
                'company_id': 1,
                'account_id': 2083,
                'payment_id': None,
                'partner_id': None,
                'currency_id': 87,
                'amount_currency': -2338000.0,
                'debit': 0.0,
                'credit': 1508.39,
                'balance': -1508.39,
                'move_name': 'CH-I/2023/09/0003',
                'company_currency_id': 2,
                'partner_name': None,
                'move_type': 'entry',
                'account_code': '1111299',
                'account_name': 'Yasir Mohammed NEO 3851',
                'journal_code': 'MIC',
                'journal_name': 'Miscellaneous',
                'full_rec_name': None,
                'column_group_key': "(('forced_options', (('date', (('date_from', '2023-01-01'), ('date_to', '2023-12-31'), ('filter', 'this_year'), ('mode', 'range'), ('period_type', 'fiscalyear'), ('string', '2023'))),)), ('horizontal_groupby_element', ()))"
            }
        }, (3529, datetime.date(2023, 9, 2)): {
            "(('forced_options', (('date', (('date_from', '2023-01-01'), ('date_to', '2023-12-31'), ('filter', 'this_year'), ('mode', 'range'), ('period_type', 'fiscalyear'), ('string', '2023'))),)), ('horizontal_groupby_element', ()))": {
                'id': 3529,
                'date': datetime.date(2023, 9, 2),
                'date_maturity': None,
                'name': 'توصيل ',
                'ref': None,
                'company_id': 1,
                'account_id': 2083,
                'payment_id': None,
                'partner_id': None,
                'currency_id': 87,
                'amount_currency': -581000.0,
                'debit': 0.0,
                'credit': 374.84,
                'balance': -374.84,
                'move_name': 'CH-I/2023/09/0003',
                'company_currency_id': 2,
                'partner_name': None,
                'move_type': 'entry',
                'account_code': '1111299',
                'account_name': 'Yasir Mohammed NEO 3851',
                'journal_code': 'MIC',
                'journal_name': 'Miscellaneous',
                'full_rec_name': None,
                'column_group_key': "(('forced_options', (('date', (('date_from', '2023-01-01'), ('date_to', '2023-12-31'), ('filter', 'this_year'), ('mode', 'range'), ('period_type', 'fiscalyear'), ('string', '2023'))),)), ('horizontal_groupby_element', ()))"
            }
        }, (3530, datetime.date(2023, 9, 2)): {
            "(('forced_options', (('date', (('date_from', '2023-01-01'), ('date_to', '2023-12-31'), ('filter', 'this_year'), ('mode', 'range'), ('period_type', 'fiscalyear'), ('string', '2023'))),)), ('horizontal_groupby_element', ()))": {
                'id': 3530,
                'date': datetime.date(2023, 9, 2),
                'date_maturity': None,
                'name': 'توصيل',
                'ref': None,
                'company_id': 1,
                'account_id': 2083,
                'payment_id': None,
                'partner_id': None,
                'currency_id': 87,
                'amount_currency': -2338000.0,
                'debit': 0.0,
                'credit': 1508.39,
                'balance': -1508.39,
                'move_name': 'CH-I/2023/09/0003',
                'company_currency_id': 2,
                'partner_name': None,
                'move_type': 'entry',
                'account_code': '1111299',
                'account_name': 'Yasir Mohammed NEO 3851',
                'journal_code': 'MIC',
                'journal_name': 'Miscellaneous',
                'full_rec_name': None,
                'column_group_key': "(('forced_options', (('date', (('date_from', '2023-01-01'), ('date_to', '2023-12-31'), ('filter', 'this_year'), ('mode', 'range'), ('period_type', 'fiscalyear'), ('string', '2023'))),)), ('horizontal_groupby_element', ()))"
            }
        }, (3531, datetime.date(2023, 9, 2)): {
            "(('forced_options', (('date', (('date_from', '2023-01-01'), ('date_to', '2023-12-31'), ('filter', 'this_year'), ('mode', 'range'), ('period_type', 'fiscalyear'), ('string', '2023'))),)), ('horizontal_groupby_element', ()))": {
                'id': 3531,
                'date': datetime.date(2023, 9, 2),
                'date_maturity': None,
                'name': 'فندق سوبوت',
                'ref': None,
                'company_id': 1,
                'account_id': 2083,
                'payment_id': None,
                'partner_id': None,
                'currency_id': 87,
                'amount_currency': -2730000.0,
                'debit': 0.0,
                'credit': 1761.29,
                'balance': -1761.29,
                'move_name': 'CH-I/2023/09/0003',
                'company_currency_id': 2,
                'partner_name': None,
                'move_type': 'entry',
                'account_code': '1111299',
                'account_name': 'Yasir Mohammed NEO 3851',
                'journal_code': 'MIC',
                'journal_name': 'Miscellaneous',
                'full_rec_name': None,
                'column_group_key': "(('forced_options', (('date', (('date_from', '2023-01-01'), ('date_to', '2023-12-31'), ('filter', 'this_year'), ('mode', 'range'), ('period_type', 'fiscalyear'), ('string', '2023'))),)), ('horizontal_groupby_element', ()))"
            }
        }, (3534, datetime.date(2023, 9, 2)): {
            "(('forced_options', (('date', (('date_from', '2023-01-01'), ('date_to', '2023-12-31'), ('filter', 'this_year'), ('mode', 'range'), ('period_type', 'fiscalyear'), ('string', '2023'))),)), ('horizontal_groupby_element', ()))": {
                'id': 3534,
                'date': datetime.date(2023, 9, 2),
                'date_maturity': datetime.date(2023, 9, 2),
                'name': 'Transfer to Yasir Mohammed NEO 3851',
                'ref': 'تعزيز من عمار بورصة',
                'company_id': 1,
                'account_id': 2083,
                'payment_id': 633,
                'partner_id': 1,
                'currency_id': 87,
                'amount_currency': 9900000.0,
                'debit': 6470.59,
                'credit': 0.0,
                'balance': 6470.59,
                'move_name': 'PNEO-H/2023/00001',
                'company_currency_id': 2,
                'partner_name': 'Qaser Al Maraya',
                'move_type': 'entry',
                'account_code': '1111299',
                'account_name': 'Yasir Mohammed NEO 3851',
                'journal_code': 'NEO-H',
                'journal_name': 'Yasir Mohammed NEO 3851',
                'full_rec_name': None,
                'column_group_key': "(('forced_options', (('date', (('date_from', '2023-01-01'), ('date_to', '2023-12-31'), ('filter', 'this_year'), ('mode', 'range'), ('period_type', 'fiscalyear'), ('string', '2023'))),)), ('horizontal_groupby_element', ()))"
            }
        }, (4187, datetime.date(2023, 9, 4)): {
            "(('forced_options', (('date', (('date_from', '2023-01-01'), ('date_to', '2023-12-31'), ('filter', 'this_year'), ('mode', 'range'), ('period_type', 'fiscalyear'), ('string', '2023'))),)), ('horizontal_groupby_element', ()))": {
                'id': 4187,
                'date': datetime.date(2023, 9, 4),
                'date_maturity': datetime.date(2023, 9, 4),
                'name': 'Customer Reimbursement 1,913,000.000\xa0 ع.د - yasir mohammed neo 3851 - 04/09/2023',
                'ref': None,
                'company_id': 1,
                'account_id': 2083,
                'payment_id': 755,
                'partner_id': 6982,
                'currency_id': 87,
                'amount_currency': -1913000.0,
                'debit': 0.0,
                'credit': 1234.19,
                'balance': -1234.19,
                'move_name': 'PNEO-H/2023/00002',
                'company_currency_id': 2,
                'partner_name': 'yasir mohammed neo 3851',
                'move_type': 'entry',
                'account_code': '1111299',
                'account_name': 'Yasir Mohammed NEO 3851',
                'journal_code': 'NEO-H',
                'journal_name': 'Yasir Mohammed NEO 3851',
                'full_rec_name': None,
                'column_group_key': "(('forced_options', (('date', (('date_from', '2023-01-01'), ('date_to', '2023-12-31'), ('filter', 'this_year'), ('mode', 'range'), ('period_type', 'fiscalyear'), ('string', '2023'))),)), ('horizontal_groupby_element', ()))"
            }
        }, (9411, datetime.date(2023, 10, 9)): {
            "(('forced_options', (('date', (('date_from', '2023-01-01'), ('date_to', '2023-12-31'), ('filter', 'this_year'), ('mode', 'range'), ('period_type', 'fiscalyear'), ('string', '2023'))),)), ('horizontal_groupby_element', ()))": {
                'id': 9411,
                'date': datetime.date(2023, 10, 9),
                'date_maturity': None,
                'name': None,
                'ref': None,
                'company_id': 1,
                'account_id': 2083,
                'payment_id': None,
                'partner_id': None,
                'currency_id': 87,
                'amount_currency': -129409.0,
                'debit': 0.0,
                'credit': 83.49,
                'balance': -83.49,
                'move_name': 'CH-I/2023/10/0015',
                'company_currency_id': 2,
                'partner_name': None,
                'move_type': 'entry',
                'account_code': '1111299',
                'account_name': 'Yasir Mohammed NEO 3851',
                'journal_code': 'MIC',
                'journal_name': 'Miscellaneous',
                'full_rec_name': None,
                'column_group_key': "(('forced_options', (('date', (('date_from', '2023-01-01'), ('date_to', '2023-12-31'), ('filter', 'this_year'), ('mode', 'range'), ('period_type', 'fiscalyear'), ('string', '2023'))),)), ('horizontal_groupby_element', ()))"
            }
        }
    }
}